<?php
declare(strict_types=1);
require __DIR__ . '/koneksi.php'; require_once __DIR__ . '/fungsi/auth.php'; require_once __DIR__ . '/fungsi/pengaturan-publik.php'; require_once __DIR__ . '/fungsi/audit.php';
wajibRole('superadmin'); siapkanPengaturanPublik($conn); $data=ambilPengaturanPublik($conn); $pesan='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $nama=trim((string)($_POST['nama_situs']??'')); $judul=trim((string)($_POST['judul_hero']??'')); $deskripsi=trim((string)($_POST['deskripsi_hero']??'')); $tombol=trim((string)($_POST['teks_tombol']??''));
    $awal=preg_match('/^#[0-9a-fA-F]{6}$/',(string)($_POST['warna_utama']??''))?$_POST['warna_utama']:'#2563eb'; $hero=preg_match('/^#[0-9a-fA-F]{6}$/',(string)($_POST['warna_hero']??''))?$_POST['warna_hero']:'#0f172a';
    $stmt=mysqli_prepare($conn,'UPDATE pengaturan_publik SET nama_situs=?, judul_hero=?, deskripsi_hero=?, teks_tombol=?, warna_utama=?, warna_hero=? WHERE id=1'); mysqli_stmt_bind_param($stmt,'ssssss',$nama,$judul,$deskripsi,$tombol,$awal,$hero);
    if($stmt && mysqli_stmt_execute($stmt)){ $data=ambilPengaturanPublik($conn); $pesan='Tampilan halaman publik berhasil disimpan.'; catatAktivitas($conn,'Mengubah tampilan halaman publik.'); } else $pesan='Pengaturan gagal disimpan.'; if($stmt)mysqli_stmt_close($stmt);
}
$judulHalaman='Pengaturan Halaman Publik'; $subjudulHalaman='Atur tampilan halaman publik tanpa coding.'; $halamanAktif='pengaturan-publik'; require __DIR__.'/partials/atas.php';
?><section class="form-card"><div class="form-card-header"><h2>Konten Halaman Publik</h2><p>Perubahan langsung terlihat oleh pengunjung.</p></div><div class="form-body"><?php if($pesan):?><div class="alert" role="status"><?=htmlspecialchars($pesan);?></div><?php endif;?><form method="POST"><div class="form-grid"><div class="form-group"><label>Nama Situs</label><input name="nama_situs" value="<?=htmlspecialchars($data['nama_situs']??'Profil Karyawan');?>" required></div><div class="form-group"><label>Teks Tombol Hero</label><input name="teks_tombol" value="<?=htmlspecialchars($data['teks_tombol']??'Lihat Data Karyawan');?>" required></div><div class="form-group full-width"><label>Judul Hero</label><input name="judul_hero" value="<?=htmlspecialchars($data['judul_hero']??'Profil Pekerja Perusahaan');?>" required></div><div class="form-group full-width"><label>Deskripsi Hero</label><textarea name="deskripsi_hero" rows="4" required><?=htmlspecialchars($data['deskripsi_hero']??'');?></textarea></div><div class="form-group"><label>Warna Utama</label><input type="color" name="warna_utama" value="<?=htmlspecialchars($data['warna_utama']??'#2563eb');?>"></div><div class="form-group"><label>Warna Latar Hero</label><input type="color" name="warna_hero" value="<?=htmlspecialchars($data['warna_hero']??'#0f172a');?>"></div></div><div class="form-actions"><a href="index.php" class="btn btn-secondary">Batal</a><button class="btn btn-success">Simpan Tampilan</button></div></form></div></section><?php require __DIR__.'/partials/bawah.php'; ?>
