CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(20) NOT NULL,
    name VARCHAR(150) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
