CREATE TABLE IF NOT EXISTS overtime_reports (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    karyawan_id INT NOT NULL,
    department_id INT UNSIGNED NOT NULL,
    dibuat_oleh_pic INT NOT NULL,
    mulai_at DATETIME NOT NULL,
    selesai_at DATETIME NOT NULL,
    total_menit INT UNSIGNED NOT NULL DEFAULT 0,
    deskripsi TEXT NULL,
    status ENUM('draft', 'menunggu_koordinator', 'menunggu_manager', 'disetujui', 'ditolak', 'selesai') NOT NULL DEFAULT 'draft',
    submitted_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_overtime_karyawan (karyawan_id),
    KEY idx_overtime_department (department_id),
    KEY idx_overtime_status (status),
    CONSTRAINT fk_overtime_karyawan FOREIGN KEY (karyawan_id) REFERENCES karyawan (id) ON DELETE RESTRICT,
    CONSTRAINT fk_overtime_department FOREIGN KEY (department_id) REFERENCES master_departemen (id) ON DELETE RESTRICT,
    CONSTRAINT fk_overtime_pic FOREIGN KEY (dibuat_oleh_pic) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
