from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

OUT = Path('output/pdf/ConstComp Dashboard Docs - Lengkap.pdf')
OUT.parent.mkdir(parents=True, exist_ok=True)

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='TitleID', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=21, leading=26, alignment=TA_CENTER, spaceAfter=16))
styles.add(ParagraphStyle(name='H1ID', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=15, leading=19, textColor=colors.HexColor('#17365D'), spaceBefore=10, spaceAfter=8))
styles.add(ParagraphStyle(name='H2ID', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=11.5, leading=15, textColor=colors.HexColor('#1F4E79'), spaceBefore=8, spaceAfter=5))
styles.add(ParagraphStyle(name='BodyID', parent=styles['BodyText'], fontName='Helvetica', fontSize=9, leading=13, spaceAfter=6))
styles.add(ParagraphStyle(name='SmallID', parent=styles['BodyText'], fontName='Helvetica', fontSize=7.7, leading=10))

def P(t, style='BodyID'):
    return Paragraph(t, styles[style])

def table(headers, rows, widths):
    data = [[P(h, 'SmallID') for h in headers]] + [[P(str(c), 'SmallID') for c in r] for r in rows]
    t = Table(data, colWidths=widths, repeatRows=1, hAlign='LEFT')
    t.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),colors.HexColor('#1F4E79')), ('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'), ('GRID',(0,0),(-1,-1),0.35,colors.HexColor('#AAB7C4')),
        ('VALIGN',(0,0),(-1,-1),'TOP'), ('LEFTPADDING',(0,0),(-1,-1),5), ('RIGHTPADDING',(0,0),(-1,-1),5),
        ('TOPPADDING',(0,0),(-1,-1),4), ('BOTTOMPADDING',(0,0),(-1,-1),4),
        ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F4F7FA')])
    ]))
    return t

def footer(canvas, doc):
    canvas.saveState(); canvas.setFont('Helvetica', 8); canvas.setFillColor(colors.HexColor('#666666'))
    canvas.drawString(2*cm, 1.15*cm, 'ConsComp Dashboard - Dokumentasi Sistem')
    canvas.drawRightString(A4[0]-2*cm, 1.15*cm, f'Halaman {doc.page}')
    canvas.restoreState()

story=[]
story += [Spacer(1, 4*cm), P('Dokumentasi Sistem', 'TitleID'), P('ConsComp Dashboard', 'TitleID'), Spacer(1, .8*cm), P('Versi lengkap - bagian placeholder telah diisi berdasarkan source code proyek.', 'BodyID'), Spacer(1, 8*cm), P('Catatan: struktur kolom dan foreign key perlu dikonfirmasi pada database MySQL aktif karena dump skema tidak tersedia di repositori.', 'SmallID'), PageBreak()]
story += [P('Daftar Isi','H1ID'), P('1. Pendahuluan<br/>2. Deskripsi Sistem<br/>3. Kebutuhan Sistem<br/>4. Perancangan Sistem<br/>5. Panduan Sistem<br/>6. Testing dan Validasi','BodyID'), P('Bab 1. Pendahuluan','H1ID'), P('Sistem Dashboard Kelola Karyawan adalah aplikasi web PHP dan MySQL untuk mengelola identitas karyawan, struktur organisasi, penilaian performa, upah, lembur, izin, cuti, dokumen, ekspor data, serta audit aktivitas. Akses dibatasi menurut role dan, bagi role operasional, menurut departemen.', 'BodyID'), P('Tujuan Sistem','H2ID'), P('Sistem menyediakan satu sumber data utama untuk administrasi SDM, mempercepat pencarian dan pembaruan informasi, mendukung proses persetujuan operasional, serta menjaga akuntabilitas melalui login, otorisasi, dan audit aktivitas.', 'BodyID'), P('Ruang Lingkup','H2ID'), P('Cakupan meliputi halaman publik, login/logout, dashboard internal, data dan profil karyawan, master data, pengupahan dan slip gaji, lembur, izin/cuti, performa, analisis, pengguna, audit, personalisasi tampilan, impor, ekspor, sinkronisasi CSV, serta dokumen PDF.', 'BodyID'), PageBreak()]
story += [P('Bab 2. Deskripsi Sistem','H1ID'), P('Arsitektur aplikasi menggunakan browser sebagai antarmuka, PHP sebagai pemroses permintaan dan logika bisnis, MySQL sebagai sumber data utama, serta penyimpanan berkas untuk media, hasil ekspor, dan dokumen. Chart.js digunakan untuk grafik, Dompdf untuk dokumen PDF, dan ZipArchive untuk ekspor XLSX.', 'BodyID'), P('Fungsi Sistem','H2ID'), table(['No.','Fungsi','Ringkasan'], [('1','Autentikasi','Login, logout, session, pembatasan role dan departemen.'),('2','Data karyawan','CRUD karyawan, media, riwayat, promosi, dan performa.'),('3','Operasional','Lembur, izin, cuti, pengganti, notifikasi, dan persetujuan.'),('4','Pengupahan','Profil gaji, komponen, pendapatan, potongan, dan slip gaji.'),('5','Administrasi','Master data, pengguna, audit, personalisasi, impor/ekspor.')],[1*cm,4*cm,11.8*cm]), Spacer(1,.2*cm), P('Batasan Sistem','H2ID'), P('Belum ada integrasi fingerprint, aplikasi mobile, webhook, SSO, email, atau layanan eksternal. CSV berfungsi sebagai mirror; perubahan utama dilakukan melalui aplikasi dan tersimpan di MySQL. Perhitungan PPh 21 belum tersedia.', 'BodyID'), PageBreak()]
story += [P('Bab 3. Kebutuhan Sistem','H1ID'), P('Kebutuhan fungsional utama mencakup autentikasi, dashboard statistik, pencarian dan pagination, pengelolaan karyawan, master data, lembur, izin, cuti, upah, slip gaji, impor/ekspor, dan audit. Kebutuhan nonfungsional mencakup session aman, verifikasi password dan status akun, otorisasi role/departemen, prepared statement, NIK unik, transaksi pada proses penting, serta kompatibilitas browser modern.', 'BodyID'), P('Ketergantungan Komponen','H2ID'), table(['Komponen','Peran','Dampak bila tidak tersedia'], [('MySQL/mysqli','Data utama aplikasi','Login dan modul data tidak berjalan.'),('PHP dan Apache/Laragon','Menjalankan halaman dan logika','Aplikasi tidak dapat diproses.'),('Composer/Dompdf','Dokumen PDF','Slip gaji atau CV PDF gagal dibuat.'),('ZipArchive','Ekspor XLSX','Berkas Excel tidak dapat dibuat.'),('Chart.js CDN','Visualisasi grafik','Data tersedia, grafik dapat gagal dimuat.')],[3*cm,5.2*cm,8.6*cm]), PageBreak()]
story += [P('Bab 4. Perancangan Sistem','H1ID'), P('4.1 Gambaran Umum Arsitektur','H2ID'), P('Pengguna mengakses halaman publik atau dashboard melalui browser. Permintaan menuju halaman PHP pada folder Dashboard. Untuk halaman internal, auth.php memeriksa session, role, dan department_id. Jika lolos, modul menjalankan query MySQL melalui mysqli, melakukan validasi formulir, menyimpan perubahan, kemudian mencatat aktivitas yang relevan. Hasil dapat ditampilkan sebagai halaman HTML, berkas XLSX, CSV, atau PDF.', 'BodyID'), P('4.2 Pengelolaan dan Relasi Data','H2ID'), P('Tabel berikut adalah tabel inti yang teridentifikasi dari source code. Nama kolom ditulis sebagai contoh bidang utama; tipe data, seluruh kolom, dan foreign key wajib diverifikasi pada database aktif.', 'BodyID'), table(['Tabel','Kolom utama','Relasi/penggunaan'], [('users','id, username, password, nama, role, department_id','Role pengguna; department_id mengacu master_departemen.'),('karyawan','id, emp_id, nik, employee_name, position, department_id','Data pusat; terhubung ke upah, riwayat, performa, izin, cuti, lembur.'),('master_departemen','id, nama, is_active','Referensi departemen untuk karyawan dan users.'),('master_posisi / master_posisi_departemen','id, nama / posisi_id, department_id','Daftar posisi dan relasinya dengan departemen.'),('profil_gaji / komponen_gaji_karyawan','id, karyawan_id / profil_gaji_id, jenis_komponen_id, nilai','Profil serta komponen pengupahan.'),('slip_gaji / slip_gaji_items','id, periode_gaji_id, karyawan_id / slip_gaji_id','Hasil perhitungan gaji dan rincian item.'),('overtime_reports / overtime_approvals','id, karyawan_id, department_id / overtime_id','Laporan lembur dan tahapan persetujuan.'),('izin_meninggalkan_pekerjaan / izin_cuti','id, karyawan_id, pengganti_id, status','Pengajuan operasional dan status persetujuan.'),('audit_aktivitas','id, user_id, aktivitas, dibuat_pada','Jejak aktivitas pengguna.')],[4.2*cm,5.1*cm,7.5*cm]), PageBreak()]
story += [P('4.3 Perancangan Komponen Aplikasi','H2ID'), table(['Modul','Komponen utama','Fungsi'], [('Antarmuka','Browser, HTML, CSS, JavaScript','Menyajikan halaman dan menerima input.'),('Halaman aplikasi','index.php, Dashboard/*.php','Memproses permintaan dan menampilkan data.'),('Keamanan','auth.php, session, CSRF','Login, role, cakupan departemen, validasi formulir.'),('Karyawan','karyawan, profil, tambah/edit/hapus','Mengelola data, media, riwayat, promosi, performa.'),('Operasional','lembur, izin, cuti, notifikasi','Pengajuan dan persetujuan kegiatan.'),('Pengupahan','upah, slip, batch slip','Komponen gaji dan pembuatan slip.'),('Administrasi','master data, pengguna, audit','Referensi sistem dan pengawasan.'),('Pertukaran data','impor, ekspor, sinkronisasi','XLSX dan CSV mirror.')],[3*cm,5.5*cm,8.3*cm]), P('4.4 Hak Akses Pengguna','H2ID'), table(['Role','Hak akses utama','Batasan'], [('superadmin','Seluruh modul, pengguna, master data, audit, impor.','Tidak mengubah/menghapus akun superadmin dari daftar pengguna.'),('admin','Dashboard, karyawan, upah, slip, lembur, izin, cuti, ekspor.','Tidak mengelola pengguna, master data, audit, personalisasi, impor.'),('direktur / manager','Dashboard, analisis dan operasional departemen.','Data dibatasi departemen; tidak CRUD karyawan.'),('koordinator','Data dan persetujuan operasional departemen.','Tidak mengelola administrasi sistem.'),('PIC','Lembur, izin, cuti, notifikasi, ekspor terkait.','Tidak membuka dashboard, data karyawan, upah, administrasi.')],[3*cm,7*cm,6.8*cm]), PageBreak()]
story += [P('4.5 Use Case dan Skenario Aktor','H2ID'), P('Semua proses internal dimulai dengan login. Sistem memeriksa session, role, dan department_id sebelum mengizinkan halaman atau query data. PIC membuat pengajuan; koordinator dan manager/direktur memproses tahapan persetujuan sesuai status. Superadmin dapat melakukan keputusan langsung pada fungsi administratif tertentu.', 'BodyID'), P('Bab 5. Panduan Sistem','H1ID'), P('5.1 Panduan Umum','H2ID'), table(['Fitur','Langkah penggunaan'], [('Halaman publik','Buka halaman utama, gunakan pencarian atau filter departemen, kemudian pilih profil karyawan yang tersedia untuk publik.'),('Login dashboard','Klik Admin, masukkan username dan password, lalu klik Masuk ke Dashboard. Sistem mengarahkan pengguna sesuai role.'),('Logout','Klik tombol Logout pada panel pengguna. Session dihentikan dan pengguna diarahkan ke login.'),('Ekspor data','Buka modul yang menyediakan ekspor, terapkan filter bila perlu, klik Ekspor, lalu simpan XLSX yang dibuat sistem.'),('Tema','Klik tombol tema di kanan atas untuk berpindah antara mode terang dan gelap.')],[4*cm,12.8*cm]), P('5.2 Pengguna sebagai Superadmin','H2ID'), P('Superadmin menggunakan menu dashboard untuk melihat ringkasan jumlah karyawan, departemen, performa, dan grafik. Dari sidebar, superadmin dapat mengelola data karyawan, master data, pengguna, pengaturan publik, audit aktivitas, upah, slip gaji, lembur, izin, cuti, analisis, impor, serta ekspor.', 'BodyID'), PageBreak()]
story += [P('Panduan Modul Superadmin','H1ID'), table(['Halaman','Langkah utama','Hasil'], [('Dashboard','Buka Dashboard dan pilih rentang/filter yang tersedia.','Statistik dan grafik ringkas tampil.'),('Data karyawan','Pilih Data Karyawan; gunakan Tambah/Edit/Hapus sesuai kewenangan.','Data dan riwayat karyawan tersimpan.'),('Master Data','Kelola departemen, posisi, relasi posisi-departemen, status kerja, dan agama.','Referensi tersedia pada formulir terkait.'),('Pengguna','Tambahkan atau ubah username, nama, role, dan departemen pengguna.','Akun memiliki cakupan akses yang sesuai.'),('Upah & Slip Gaji','Buka Upah, tetapkan profil/komponen; buat slip individu atau batch.','Rincian pengupahan dan PDF slip dapat dibuat.'),('Lembur, Izin & Cuti','Buka modul terkait, tinjau data, lalu proses status sesuai wewenang.','Status pengajuan dan approval diperbarui.'),('Audit Aktivitas','Buka Audit Aktivitas dan gunakan filter/pencarian jika tersedia.','Jejak tindakan pengguna dapat ditinjau.'),('Personalisasi Publik','Buka Pengaturan Publik dan simpan perubahan tampilan/informasi.','Halaman publik mengikuti konfigurasi terbaru.')],[3.4*cm,8.3*cm,5.1*cm]), P('Catatan penggunaan','H2ID'), P('Selalu pastikan data departemen dan role pengguna telah tepat sebelum menyimpan. Untuk tindakan yang mengubah data, periksa pesan keberhasilan atau kegagalan dari sistem. Pengujian langsung diperlukan untuk memastikan konfigurasi database dan hak akses pada lingkungan yang digunakan.', 'BodyID'), PageBreak()]
story += [P('Bab 6. Testing dan Validasi','H1ID'), P('Pengujian dilakukan per halaman, fungsi, akses, dan konfigurasi. Setiap hasil aktual perlu diisi setelah aplikasi dijalankan pada lingkungan yang memiliki database uji. Kolom “hasil yang diharapkan” berikut menjadi kriteria validasi.', 'BodyID'), table(['ID','Tahapan pengujian','Hasil yang diharapkan'], [('TST-01','Login dengan username/password benar dan akun aktif.','Masuk ke halaman sesuai role dan session terbentuk.'),('TST-02','Login dengan password salah atau akun tidak aktif.','Akses ditolak dan pesan kesalahan tampil.'),('TST-03','Akses halaman internal tanpa login.','Pengguna dialihkan/ditolak oleh pemeriksaan autentikasi.'),('TST-04','Role terbatas membuka halaman admin atau master data.','Akses ditolak sesuai wajibRole().'),('TST-05','Role operasional membuka data departemen lain.','Query/halaman hanya menampilkan data departemen sendiri.'),('TST-06','Tambah dan edit data karyawan dengan NIK yang sama.','Duplikasi NIK ditolak; data valid tersimpan.'),('TST-07','Buat laporan lembur lalu lakukan approval berurutan.','Tahap dan status berubah sesuai role persetuju.'),('TST-08','Ajukan izin/cuti dengan karyawan pengganti.','Pengajuan tersimpan dan status dapat ditinjau.'),('TST-09','Simpan profil upah dan generate slip gaji.','Komponen tersimpan konsisten dan slip dapat dibuat.'),('TST-10','Ekspor data dari modul yang diizinkan.','Berkas XLSX terunduh dengan data sesuai cakupan.'),('TST-11','Logout lalu buka ulang URL halaman internal.','Session berakhir dan halaman tidak dapat diakses.'),('TST-12','Uji PHP, MySQL, mysqli, ZipArchive, Composer/Dompdf.','Aplikasi, ekspor XLSX, dan PDF berjalan tanpa error.')],[1.4*cm,8.3*cm,7.1*cm]), Spacer(1,.4*cm), P('Status dokumentasi: semua placeholder teks pada dokumen sumber telah diisi. Screenshot halaman dan hasil aktual pengujian memerlukan aplikasi yang berjalan dengan database uji.', 'BodyID')]

doc = SimpleDocTemplate(str(OUT), pagesize=A4, rightMargin=1.7*cm, leftMargin=1.7*cm, topMargin=1.7*cm, bottomMargin=1.8*cm, title='ConstComp Dashboard Docs - Lengkap')
doc.build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT.resolve())
